version: "3.8"

services:
  app:
    build:
        context: ./backend/app/
        dockerfile: Dockerfile
    env_file:
      - ./backend/app/app/core/.env
    volumes:
        - ./backend/:/backend/
    ports:
      - "8000:8000"
    command: uvicorn app.app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    depends_on:
        - db

  db:
    image: postgres:14-alpine
    env_file:
      - ./backend/app/app/core/.env
    volumes:
        - postgres_data:/var/lib/postgresql/data/
    ports:
        - '5432:5432'

  quasar:
    build:
        context: .
        target: 'develop-stage'
    ports:
        - '8080:8080'
    volumes:
        - '.:/thebiohack'
    command: /bin/sh -c "yarn && quasar dev"

volumes:
    postgres_data:
