version: '3.9'

services:
    db:
        image: postgres:14
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
            - ./backend/app/application/core/.env
        ports:
            - "5432:5432"
    web:
        build:
            context: ./backend/app
            dockerfile: Dockerfile
        volumes:
            - ./backend/app/:/app/
        command: bash -c "alembic upgrade head && uvicorn application.main:app --reload --workers 1 --host 0.0.0.0 --port 8000"
        env_file:
            - ./backend/app/application/core/.env
        ports:
            - "8000:8000"
        depends_on:
            - db


    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4
        environment:
            - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
            - PGADMIN_DEFAULT_PASSWORD=admin
        ports:
            - "5050:80"
        depends_on:
            - db

    quasar:
        build:
            context: .
            target: 'develop-stage'
        ports:
            - '8080:8080'
        volumes:
            - '.:/thebiohack'
        command: /bin/sh -c "yarn && quasar dev"


volumes:
    postgres_data:
