version: "3.9"

services:
  app:
    build: ../app1
    env_file:
      - app/core/.env
    ports:
      - "8000:8000"


  database:
    image: postgres:12
    env_file:
      - app/core/.env
    ports:
      - "5432:5432"

